global:
  scrape_interval:     15s

  external_labels:
    monitor: 'railway-prom'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s

    static_configs:
      - targets: ['notion-echo-staging.up.railway.app']
